SELECT * FROM DEPARTMENTS;

SELECT FIRST_NAME NAME FROM EMPLOYEES;

SELECT DISTINCT job_id AS JOB From EMPLOYEES;

SELECT EMPLOYEE_ID,(END_DATE - START_DATE)/365 FROM JOB_HISTORY;

SELECT CITY FROM LOCATIONS WHERE COUNTRY_ID<>'US';

SELECT FIRST_NAME AS NAME, HIRE_DATE FROM EMPLOYEES ORDER BY HIRE_DATE DESC, NAME;

SELECT SYSDATE FROM DUAL;--pseudo column

SELECT 2*5 FROM DUAL;

SELECT job_title AS Title FROM JOBS WHERE MAX_SALARY>25000 OR MIN_SALARY<5000;

SELECT 'is true' AS CONDITION FROM DUAL WHERE 0=0 OR 1=0 AND 0=1;

SELECT job_title AS Title FROM JOBS WHERE MAX_SALARY BETWEEN 10000 AND 15000; --include border

SELECT job_title AS Title FROM JOBS WHERE MIN_SALARY IN (4200,8200);

SELECT job_title AS Title FROM JOBS WHERE job_title LIKE '%Manager%';

SELECT FIRST_NAME AS NAME, HIRE_DATE FROM EMPLOYEES WHERE FIRST_NAME LIKE '_i%';
/* 
CASE 
WHEN THEN 
     ELSE 
*/
SELECT job_title AS Title, 
CASE WHEN MIN_SALARY<5000 THEN 'Low'
     WHEN MIN_SALARY BETWEEN 5000 AND 10000 THEN 'Medium'
     WHEN MIN_SALARY>10000 THEN 'High'
     END AS salary
              FROM JOBS ORDER BY salary;


SELECT department_name FROM DEPARTMENTS WHERE location_id IN(
      SELECT location_id FROM LOCATIONS WHERE city IN ('Beijing','Roma', 'Tokyo', 'Seattle')
);

SELECT department_name FROM DEPARTMENTS WHERE MANAGER_ID IS NOT NULL;